[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0

; Force compilation flags to route serial logging output over native USB CDC
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Required libraries for Project Lunagrid features
lib_deps =
    knolleary/PubSubClient @ ^2.8
